[package]
name = "wit-bindgen-cli"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version.workspace = true
edition = { workspace = true }
repository = 'https://github.com/bytecodealliance/wit-bindgen'
license = "Apache-2.0 WITH LLVM-exception"
homepage = 'https://github.com/bytecodealliance/wit-bindgen'
description = """
CLI tool to generate bindings for WIT documents and the component model.
"""

[workspace]
members = [
  "crates/test-rust-wasm",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.19.1"

[workspace.dependencies]
anyhow = "1.0.72"
bitflags = "2.3.3"
heck = { version = "0.4", features = ["unicode"] }
pulldown-cmark = { version = "0.9", default-features = false }
clap = { version = "4.3.19", features = ["derive"] }
env_logger = "0.10.0"
indexmap = "2.0.0"

wasmparser    = { git = "https://github.com/wasmfx/wasmfx-tools", tag = "wasmfx-tools-1.0.60" }
wasm-metadata = { git = "https://github.com/wasmfx/wasmfx-tools", tag = "wasmfx-tools-1.0.60" }
wasm-encoder  = { git = "https://github.com/wasmfx/wasmfx-tools", tag = "wasmfx-tools-1.0.60" }
wit-parser    = { git = "https://github.com/wasmfx/wasmfx-tools", tag = "wasmfx-tools-1.0.60" }
wit-component = { git = "https://github.com/wasmfx/wasmfx-tools", tag = "wasmfx-tools-1.0.60" }

wit-bindgen-core = { path = 'crates/core', version = '0.19.1' }
wit-bindgen-c = { path = 'crates/c', version = '0.19.1' }
wit-bindgen-rust = { path = "crates/rust", version = "0.19.1" }
wit-bindgen-teavm-java = { path = 'crates/teavm-java', version = '0.19.1' }
wit-bindgen-go = { path = 'crates/go', version = '0.19.1' }
wit-bindgen-csharp = { path = 'crates/csharp', version = '0.19.1' }
wit-bindgen-markdown = { path = 'crates/markdown', version = '0.19.1' }
wit-bindgen = { path = 'crates/guest-rust', version = '0.19.1', default-features = false }

[[bin]]
name = "wit-bindgen"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
wit-bindgen-core = { workspace = true }
wit-bindgen-rust = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-c = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-markdown = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-teavm-java = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-go = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-csharp = { workspace = true, features = ['clap'], optional = true }
wit-component = { workspace = true }
wasm-encoder = { workspace = true }

[features]
default = [
  'c',
  'rust',
  'markdown',
  'teavm-java',
  'go',
  'csharp-naot',
]
c = ['dep:wit-bindgen-c']
rust = ['dep:wit-bindgen-rust']
markdown = ['dep:wit-bindgen-markdown']
teavm-java = ['dep:wit-bindgen-teavm-java']
go = ['dep:wit-bindgen-go']
csharp = ['dep:wit-bindgen-csharp']
csharp-naot = ['csharp']
csharp-mono = ['csharp']

[dev-dependencies]
heck = { workspace = true }
wasmtime = { version = "17.0.0", features = ['component-model'] }
wasmtime-wasi =  { version = "17.0.0" }
test-artifacts = { path = 'crates/test-rust-wasm/artifacts' }
wit-parser = { workspace = true }
wasmparser = { workspace = true }
wasm-encoder = { workspace = true }
